<div style="background: #000;
            color: #FFF;
            margin: 0px;
                padding: 10px 0px 10px 0px;
            text-align: center; 
                ">
    <h1 style="padding: 120px 120px -30px 0px;">Week 14 Lab</h1>
</div>

In [1]:
# imports

import numpy as np

## Exercise 1

Create the following numpy arrays:
    
a) An array using the following lists (make it interesting if you can)

In [5]:
l = [0,0,0,0,0] 
m = [1,2,3,4,5]

np.linspace(l,m)

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.02040816, 0.04081633, 0.06122449, 0.08163265, 0.10204082],
       [0.04081633, 0.08163265, 0.12244898, 0.16326531, 0.20408163],
       [0.06122449, 0.12244898, 0.18367347, 0.24489796, 0.30612245],
       [0.08163265, 0.16326531, 0.24489796, 0.32653061, 0.40816327],
       [0.10204082, 0.20408163, 0.30612245, 0.40816327, 0.51020408],
       [0.12244898, 0.24489796, 0.36734694, 0.48979592, 0.6122449 ],
       [0.14285714, 0.28571429, 0.42857143, 0.57142857, 0.71428571],
       [0.16326531, 0.32653061, 0.48979592, 0.65306122, 0.81632653],
       [0.18367347, 0.36734694, 0.55102041, 0.73469388, 0.91836735],
       [0.20408163, 0.40816327, 0.6122449 , 0.81632653, 1.02040816],
       [0.2244898 , 0.44897959, 0.67346939, 0.89795918, 1.12244898],
       [0.24489796, 0.48979592, 0.73469388, 0.97959184, 1.2244898 ],
       [0.26530612, 0.53061224, 0.79591837, 1.06122449, 1.32653061],
       [0.28571429, 0.57142857, 0.

b) A 3 x 4 matrix of zeros: 

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

c) A 2 x 4 matrix of zeros and ones of the following format:

[[0,0,1,1], [0,0,1,1]]

(try without using python lists)

In [19]:
zeros= np.zeros((2,2))
ones= np.ones((2,2))
print(zeros)
print(ones)
np.hstack((zeros,ones))  # a[:, 2:]=1 Two dimensional

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


array([[0., 0., 1., 1.],
       [0., 0., 1., 1.]])

e) A 3 x 4 array from the following numpy array (do not change the already existing code):

In [21]:
r = np.arange(0,12)
# enter your code below
print(r)
r.reshape(3,4)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

f) A 1 x 13 array from the following array

look into the `resize` method

In [33]:
n = np.empty(shape=(2,6))
### enter your code below
print(n)
print(np.resize(n, (1,13)))  #resize repeats from the beginning if the original shape has 
#less values than the new shape

[[ 3.10503618e+231 -3.11108461e+231  3.95252517e-323  0.00000000e+000
   0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   0.00000000e+000  0.00000000e+000]]
[[ 3.10503618e+231 -3.11108461e+231  3.95252517e-323  0.00000000e+000
   0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   3.10503618e+231]]


) using the following array, create an array that consists of the same numbers but squared and in order from smallest to largest

In [34]:
n = np.array([7, 6, 9, 5, 8, 9, 6, 10, 3, 4, 3, 3, 1, 2, 5, 8, 6, 1, 6, 0])
### enter your code below
np.sort(n**2)

array([  0,   1,   1,   4,   9,   9,   9,  16,  25,  25,  36,  36,  36,
        36,  49,  64,  64,  81,  81, 100])

## Exercise 2

Produce  the array as asked

a) Create a 3x3x3 array with the numbers from 1, 27. Then slice it to produce the 3x3 array in the middle.

In [50]:
a = np.arange(1,28).reshape(3,3,3)
a[1,:,:] #matrix, rows, columns

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [49]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

b) Create a 3 x 3 array of random numbers. Then slice it to produce the numbers in the 2-index column.

In [56]:
rng = np.random.default_rng(0)
### enter your code below 
rng.random(9).reshape(3,3)[:,1]  #rows, columns

array([0.26978671, 0.81327024, 0.72949656])

c) Create a 3x3x3 array of zeros. Slice a 2x2 array from it and change the values to 1s. Then output the original 3x3x3 with `0`'s and `1`s

In [59]:
a= np.zeros((3,3,3))
a[1,1:,1:]=1 #it does affect the original

In [60]:
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 1., 1.],
        [0., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

d) Create an array of all the numbers from 1, 27 (inclusive). Then produce a slice that outputs only the even numbers less than 14.

In [62]:
a = np.arange(1,28)
a[(a%2==0) & (a<14)]

array([ 2,  4,  6,  8, 10, 12])

## Exercise 3

a) Create an array of all postive integers from 1 to 100.    
b) Reshape it into a 10 x 10 matrix  
c) Remove multiples (so numbers that aren't prime  
d) Output the prime numbers.  

a)

b) reshape it into a 10 x 10 matrix

In [64]:
a= np.arange(1,101).reshape(10,10)
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

c) starting with 2 (until you get to sqrt(100) or 10), replace multiples of that number with 0

In [ ]:
for i in range(2,10):
    a[(a%i == 0) & (a != i)]=0
a

d) Using a slice, output your prime sieve containing all of the prime numbers less than 0 (be sure to exclude 1 from your slice)

hint: the length of such slice should be `25`

In [71]:
a[(a!=0) & (a!=1)]

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97])