### 1. Write a NumPy program to print the NumPy version in your system

In [1]:
import numpy as np

In [ ]:
np.version.version  # to get numpy version

In [ ]:
np.__version__  #same thing different method

### 2. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

In [ ]:
lst = [12.23, 13.32, 100, 36.32] 
new_array = np.array(lst)
new_array

### 3.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

Expected Output:
[[ 2 3 4] 
[ 5 6 7] 
[ 8 9 10]] 

In [ ]:
matrix = np.arange(2, 11).reshape(3,3)
matrix

In [ ]:
matrix = np.arange(2,11)   #it has to be 9 elements- start, end(not inclusive)
new_matrix = matrix.reshape(3,3)
new_matrix

### 4. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.

In [ ]:
null = np.zeros(10)
null[6] = 11
null

### 5. Write a NumPy program to create an array with values ranging from 12 to 38

In [ ]:
new_array = np.arange(12,38)
new_array

### 6. Write a NumPy program to reverse an array (first element becomes last).

In [ ]:
new_array = np.arange(12,38)
np.flip(new_array)    #x = x[::-1]

### 7. Write a NumPy program to convert an array to a float type.

In [ ]:
new_array = np.arange(1,5).astype(float)
new_array

### 8. Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 

Expected Output:
Original array: 
[[ 1. 1. 1. 1. 1.] 
................... 
[ 1. 1. 1. 1. 1.]] 
1 on the border and 0 inside in the array 
[[ 1. 1. 1. 1. 1.] 
................... 
[ 1. 1. 1. 1. 1.]]

In [ ]:
new_array = np.ones((10,10))
new_array[1:-1,1:-1] = 0  #technically is -2 but we are doing
#-1 because is not inclusive
new_array

### 9. Write a NumPy program to add a border (filled with 0's) around an existing array

In [5]:
new_array = np.ones(9).reshape(3,3)
new_array
np.pad(new_array,(2,2), 'constant', constant_values=(0,0))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

### 10. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [91]:
new_array = np.zeros((8,8))
new_array[::2, 1::2] =1
new_array[1::2] =1
new_array[1::2, 1::2] =0
new_array

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [101]:
#solution
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])