<div style="background: #000;
            color: #FFF;
            margin: 0px;
            padding: 10px 0px 20px 0px;
            text-align: center; 
                ">
    <h1>Week 24 Lab</h1>
</div>


In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Part 1 - Python Problems
<hr>

### Exercise 1

Create a function that takes a list of integers and calculates the mean. Use the following formula for calculating averages and not any `mean`/`average` method.

$$ \mu = {\frac {1}{n}}\sum _{i=1}^{n}a_{i}={\frac {a_{1}+a_{2}+\cdots +a_{n}}{n}}$$

In [12]:
example_list = [1,2,3,4,5,6,7,8,9]   #don't forget to think about edge cases

def mean_calculator(lst):
    if lst:
        return sum(lst)//len(lst)
    return 0

mean_calculator([])

0

### Exercise 2

Create a class that operates like a stack.  

a stack receives adds to the top and pops from the top

In [ ]:
LIFO--> BOX With books inside

In [99]:
#Use a list []

class Box:
    def __init__(self,lst=[]):
        self.lst= lst
        
    def __add__(self,book):
        self.lst.append(book)
    
    def __pop__(self):
        self.lst.pop()
    
    def look_inside(self):
        for i in self.lst:
            print(i)
        
box_1 = Box()
box_1.__add__("The Hunger Games")
box_1.__add__("Twilight")
box_1.__add__("Color Purple")
box_1.__add__("The Giver")
box_1.look_inside()
box_1.__pop__()
print("\n")
box_1.look_inside()

The Hunger Games
Twilight
Color Purple
The Giver


The Hunger Games
Twilight
Color Purple


### Exercise 3

Write a generator function which returns a few values and then use it to retrieve a value using `next` (the global function). 

In [13]:
nums = [1,5,14,5,4]
def generator(nums):
    for num in nums:
        yield num

a= generator(nums)

In [14]:
next(a)

1

### Exercise 4

Create a namedtuple `'Point'` that contains the points `x` and `y`.

In [100]:
from collections import namedtuple

In [106]:
Point = namedtuple('Point',['x','y'])

first_point = Point(5,2)
print(first_point.x)
first_point.y

5


2

In [ ]:
Point = namedtuple('Point',['x','y'])

class Point:
    def __init__(self,x,y):
        self.x= x
        self.y=y

### Exercise 5

Create a moving average class that:
* has a method `add` that is used to add new values
* has a method `avg` that calculates the average of the 5 most recently added values
* if theres less than 5 values the avg method should return the avg of those values
* has an attribute `values` that contain all values added
* has an attribute `window` that contains the 5 most recently added values

In [15]:
class MovingAverage:
    def __init__(self,values=[], window=[]):
        self.values =values
        self.window =window
        
    def __add__(self,value):
        self.values.append(value)
        if len(self.values)>=5:
            self.window =self.values[-5:]
        else:
            self.window=self.values
        
    def __avg__(self):
        if len(self.values)>5:
            return mean_calculator(self.window)
        return mean_calculator(self.values)
    
    
moving1 = MovingAverage()
moving1.__add__(5)
moving1.values
moving1.__add__(4)
moving1.__add__(3)
moving1.__add__(2)
moving1.__add__(1)
moving1.__add__(0)
# moving1.values
moving1.window

[4, 3, 2, 1, 0]

## Part 2 - Numpy Problems
<hr>

### Exercise 1

Using numpy, create an array that contains the values of $y$ for each of the $x$ values ranging from 0 to 100.

$$ y = 12x+4  $$

In [16]:
y = 12*np.arange(0,101) +4
y

array([   4,   16,   28,   40,   52,   64,   76,   88,  100,  112,  124,
        136,  148,  160,  172,  184,  196,  208,  220,  232,  244,  256,
        268,  280,  292,  304,  316,  328,  340,  352,  364,  376,  388,
        400,  412,  424,  436,  448,  460,  472,  484,  496,  508,  520,
        532,  544,  556,  568,  580,  592,  604,  616,  628,  640,  652,
        664,  676,  688,  700,  712,  724,  736,  748,  760,  772,  784,
        796,  808,  820,  832,  844,  856,  868,  880,  892,  904,  916,
        928,  940,  952,  964,  976,  988, 1000, 1012, 1024, 1036, 1048,
       1060, 1072, 1084, 1096, 1108, 1120, 1132, 1144, 1156, 1168, 1180,
       1192, 1204])

### Exercise 2

Create a 2-dimensional numpy array that contains the numbers from 1 to 20 with even numbers in the first column and odd numbers in the second.

In [22]:
a = np.arange(1,21)
np.array([a[a%2==0], a[a%2==1]]).T

array([[ 2,  1],
       [ 4,  3],
       [ 6,  5],
       [ 8,  7],
       [10,  9],
       [12, 11],
       [14, 13],
       [16, 15],
       [18, 17],
       [20, 19]])

### Exercise 3

Create a numpy array with random numbers between 0 and 1.

In [49]:
rng = np.random.uniform(0,1,10) #start, stop, size
rng

array([0.02919281, 0.35761832, 0.21275419, 0.92029429, 0.50626754,
       0.13190383, 0.47653847, 0.87302766, 0.84319462, 0.50286825])

### Exercise 4

Create an array that contains 100 numbers. All of them between 0 and 5. Then add that to an array that contains the numbers from 0 to 99.

In [50]:
new_array = np.linspace(0,5,100) +np.arange(0,100)
new_array

array([  0.        ,   1.05050505,   2.1010101 ,   3.15151515,
         4.2020202 ,   5.25252525,   6.3030303 ,   7.35353535,
         8.4040404 ,   9.45454545,  10.50505051,  11.55555556,
        12.60606061,  13.65656566,  14.70707071,  15.75757576,
        16.80808081,  17.85858586,  18.90909091,  19.95959596,
        21.01010101,  22.06060606,  23.11111111,  24.16161616,
        25.21212121,  26.26262626,  27.31313131,  28.36363636,
        29.41414141,  30.46464646,  31.51515152,  32.56565657,
        33.61616162,  34.66666667,  35.71717172,  36.76767677,
        37.81818182,  38.86868687,  39.91919192,  40.96969697,
        42.02020202,  43.07070707,  44.12121212,  45.17171717,
        46.22222222,  47.27272727,  48.32323232,  49.37373737,
        50.42424242,  51.47474747,  52.52525253,  53.57575758,
        54.62626263,  55.67676768,  56.72727273,  57.77777778,
        58.82828283,  59.87878788,  60.92929293,  61.97979798,
        63.03030303,  64.08080808,  65.13131313,  66.18

### Exercise 5

Create a 10 by 10 matrix containing zeros. Then create a 10 by 10 matrix containing ones. Combine the two matrices so that the new dimensions are 20 by 10.

In [59]:
zeros_matrix = np.zeros((10,10))
ones_matrix = np.ones((10,10))
mixed_matrix = np.concatenate((zeros_matrix, ones_matrix))
print(mixed_matrix.shape)
mixed_matrix


(20, 10)


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Exercise 6

Given the following numpy array, find the cumulative sum along the rows. Then find the cumulative sum along the columns. Then output the 2nd (1st index) column but only the first 10 rows. You should get a very recognizable pattern.

In [60]:
a = np.array([[0,1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10,0], [2,3,4,5,6,7,8,9,10,0,1], [3,4,5,6,7,8,9,10,0,1,2],[4,5,6,7,8,9,10,0,1,2,3],[5,6,7,8,9,10,0,1,2,3,4],[6,7,8,9,10,0,1,2,3,4,5],[7,8,9,10,0,1,2,3,4,5,6],[8,9,10,0,1,2,3,4,5,6,7],[9,10,0,1,2,3,4,5,6,7,8],[10,0,1,2,3,4,5,6,7,8,9]])
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  0],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10,  0,  1],
       [ 3,  4,  5,  6,  7,  8,  9, 10,  0,  1,  2],
       [ 4,  5,  6,  7,  8,  9, 10,  0,  1,  2,  3],
       [ 5,  6,  7,  8,  9, 10,  0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10,  0,  1,  2,  3,  4,  5],
       [ 7,  8,  9, 10,  0,  1,  2,  3,  4,  5,  6],
       [ 8,  9, 10,  0,  1,  2,  3,  4,  5,  6,  7],
       [ 9, 10,  0,  1,  2,  3,  4,  5,  6,  7,  8],
       [10,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [61]:
cumsum_row= np.cumsum(a, axis=0)
cumsum_row

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 10],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 19, 11],
       [ 6, 10, 14, 18, 22, 26, 30, 34, 27, 20, 13],
       [10, 15, 20, 25, 30, 35, 40, 34, 28, 22, 16],
       [15, 21, 27, 33, 39, 45, 40, 35, 30, 25, 20],
       [21, 28, 35, 42, 49, 45, 41, 37, 33, 29, 25],
       [28, 36, 44, 52, 49, 46, 43, 40, 37, 34, 31],
       [36, 45, 54, 52, 50, 48, 46, 44, 42, 40, 38],
       [45, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46],
       [55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55]])

In [62]:
cumsum_col = np.cumsum(a, axis=1)
cumsum_col

array([[ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55],
       [ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 55],
       [ 2,  5,  9, 14, 20, 27, 35, 44, 54, 54, 55],
       [ 3,  7, 12, 18, 25, 33, 42, 52, 52, 53, 55],
       [ 4,  9, 15, 22, 30, 39, 49, 49, 50, 52, 55],
       [ 5, 11, 18, 26, 35, 45, 45, 46, 48, 51, 55],
       [ 6, 13, 21, 30, 40, 40, 41, 43, 46, 50, 55],
       [ 7, 15, 24, 34, 34, 35, 37, 40, 44, 49, 55],
       [ 8, 17, 27, 27, 28, 30, 33, 37, 42, 48, 55],
       [ 9, 19, 19, 20, 22, 25, 29, 34, 40, 47, 55],
       [10, 10, 11, 13, 16, 20, 25, 31, 38, 46, 55]])

In [63]:
#Then output the 2nd (1st index) column but only the first 10 rows. You should get a very recognizable pattern.
a[:10,1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Exercise 7

Using the following string. Turn it into a numpy array where all the letters are their own element.

In [64]:
s = "helloworld"

In [65]:
lst = [letter for letter in s]
lst

['h', 'e', 'l', 'l', 'o', 'w', 'o', 'r', 'l', 'd']

In [66]:
#option 1
np.array(lst)

array(['h', 'e', 'l', 'l', 'o', 'w', 'o', 'r', 'l', 'd'], dtype='<U1')

In [67]:
#option 2
np.char.split(lst)

array([list(['h']), list(['e']), list(['l']), list(['l']), list(['o']),
       list(['w']), list(['o']), list(['r']), list(['l']), list(['d'])],
      dtype=object)

### Exercise 8

How would we flatten the following array?

In [68]:
a = np.eye(10)
a.flatten()

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

## Part 3 - Pandas Problems
<hr>

**1.** Create a dataframe using the following:

In [69]:
lst = [['Red',4],['Blue',6],['Green',1],\
       ['Yellow',5],['White',3],['Black',2],]


In [70]:
df = pd.DataFrame(lst, columns= ["color", "count"])

In [71]:
df

color  count
0     Red      4
1    Blue      6
2   Green      1
3  Yellow      5
4   White      3
5   Black      2

**2.** Create a dataframe using the following:

In [72]:
dct = {'red':4, 'blue':6, 'green':1,\
       'yellow':5, 'white':3, 'black':2 }


In [73]:
df = pd.DataFrame(list(dct.items()), columns= ["color","amount"])

In [74]:
df

color  amount
0     red       4
1    blue       6
2   green       1
3  yellow       5
4   white       3
5   black       2

**The following exercises will use the dataset imported below:**


In [80]:
df = pd.DataFrame([[np.nan,'Toyota','Camry',336978, 24765,np.nan],[2019,'Toyota','Corolla',304850, np.nan,4560556],[2019,'Toyota','Supra',np.nan, 35545,102511.78],[2019,np.nan,'Avalon',np.nan ,36480,1012940.16]])
df.columns = ['year', 'make', 'model', 'number sold', 'price', 'revenue (in thousands)']
df

year    make    model  number sold    price  revenue (in thousands)
0     NaN  Toyota    Camry     336978.0  24765.0                     NaN
1  2019.0  Toyota  Corolla     304850.0      NaN              4560556.00
2  2019.0  Toyota    Supra          NaN  35545.0               102511.78
3  2019.0     NaN   Avalon          NaN  36480.0              1012940.16

### Exercise 4

Fix the `year` column in the dataframe by replacing missing values with the average value of that column.

In [81]:
df["year"] = df["year"].fillna(df["year"].mean())

In [82]:
df["year"] = df["year"].astype('int32')

In [83]:
df["year"]

0    2019
1    2019
2    2019
3    2019
Name: year, dtype: int32

### Exercise 5

Fix the `'make'` column by replacing the missing value with the value that occurred most frequently (mode).

In [84]:
df["make"] = df["make"].fillna(df["make"].mode()[0])

In [85]:
df["make"]

0    Toyota
1    Toyota
2    Toyota
3    Toyota
Name: make, dtype: object

### Exercise 6

Fix the `'revenue (in thousands)'` column by calculating the approximate revenue. Remember that the value of `'revenue'` is in the 1000s.

$$ \textrm{revenue} = \textrm{number sold} * \textrm{price} $$

In [87]:
df["revenue (in thousands)"] = df["revenue (in thousands)"].fillna((df["number sold"]*df["price"])/1000)

In [88]:
df

year    make    model  number sold    price  revenue (in thousands)
0  2019  Toyota    Camry     336978.0  24765.0              8345260.17
1  2019  Toyota  Corolla     304850.0      NaN              4560556.00
2  2019  Toyota    Supra          NaN  35545.0               102511.78
3  2019  Toyota   Avalon          NaN  36480.0              1012940.16

### Exercise 7

Fix the `'price'` column by calculating the approximate price.

$$ \textrm{price} = \frac{\textrm{revenue}}{\textrm{number sold}} $$

In [89]:
df["price"] = df["price"].fillna(df["revenue (in thousands)"]*1000/df["number sold"])

In [90]:
df

year    make    model  number sold    price  revenue (in thousands)
0  2019  Toyota    Camry     336978.0  24765.0              8345260.17
1  2019  Toyota  Corolla     304850.0  14960.0              4560556.00
2  2019  Toyota    Supra          NaN  35545.0               102511.78
3  2019  Toyota   Avalon          NaN  36480.0              1012940.16

### Exercise 8

Fix the `'number sold'` column by calculating the approximate number of vehicles sold.

$$ \textrm{number sold} = \frac{\textrm{revenue}}{\textrm{price}} $$

In [91]:
df["number sold"] = df["number sold"].fillna((df["revenue (in thousands)"]*1000)/df["price"])

In [92]:
df

year    make    model  number sold    price  revenue (in thousands)
0  2019  Toyota    Camry     336978.0  24765.0              8345260.17
1  2019  Toyota  Corolla     304850.0  14960.0              4560556.00
2  2019  Toyota    Supra       2884.0  35545.0               102511.78
3  2019  Toyota   Avalon      27767.0  36480.0              1012940.16